import Plugin as PluginAPI

class SamplePlugin(PluginAPI.Plugin):

    def __init__(self, core):
        super().__init__(core)

        # Registering event processor function for later mapping configuration
        self.eventProcessingFunctions["SampleEventProcessorFunction"] = self.sample_event_processor_function
        #...
        
        # Defining default options
        self.defaultOptions : dict = {
            "Option_1" : 1
        }
        
        # Defining default event generation settings
        self.defaultGeneratedEventNames = {
            "TestEchoEvent" : ["EchoEvent_1", "EchoEvent_2"]
        }

    # Called when the plugin is loaded by the Plugin Manager
    def load(self):
        super().load()

    # Called when the plugin is unloaded (generally: right before program's shutdown)
    def unload(self):
        super().unload()
        
    # Called every core's main loop update
    def update(self, delta_time : float):
        super().update(delta_time)


    # Example event processor function
    def sample_event_processor_function(self, event : PluginAPI.Event, arguments : dict = {}):

        self.core.logger.log(f"Plugin {self.pluginName} received event {event.eventName}")
        
        # Echoing the event if it is not generated by this plugin
        if event.initiator != self.pluginName:
            echo_event = PluginAPI.Event("TestEchoEvent", self.pluginName, event.tags, event.tags)
            self.generate_event(echo_event)

