import Plugin as PluginAPI

import sqlite3
from pathlib import Path

class ViewerData(PluginAPI.Plugin):

    def __init__(self, core):
        super().__init__(core)

        # Registering event processor function for later mapping configuration
        self.eventProcessingFunctions["SampleEventProcessorFunction"] = self.sample_event_processor_function
        #...
        
        # Defining default options
        self.defaultOptions : dict = {
            "DatabasePath" : "./Resources/ViewerData/ViewerData.db"
        }
        
        self.databaseConnection : sqlite3.Connection = None
        self.cursor = None
        

    # Called when the plugin is loaded by the Plugin Manager
    def load(self):
        super().load()
        
        # Ensures that database directory exists
        directory_path = Path(self.get_option("DatabasePath")).parent
        directory_path.mkdir(exist_ok=True, parents=True)
        
        # Connecting to the database
        self.databaseConnection = sqlite3.connect(self.get_option("DatabasePath"))
        

    # Called when the plugin is unloaded (generally: right before program's shutdown)
    def unload(self):
        super().unload()
        
    # Called every core's main loop update
    def update(self, delta_time : float):
        super().update(delta_time)


    # Example event processor function
    def sample_event_processor_function(self, event : PluginAPI.Event, arguments : dict = {}):

        self.core.logger.log(f"Plugin {self.pluginName} received event {event.eventName}")
        
        # Echoing the event if it is not generated by this plugin
        if event.initiator != self.pluginName:
            echo_event = PluginAPI.Event("TestEchoEvent", self.pluginName, event.tags, event.tags)
            self.generate_event(echo_event)

