
// Wait for the HTML file to be fully loaded before running the code
document.addEventListener("DOMContentLoaded", onFileLoaded);

function onFileLoaded()
{
    // setInterval(() => {
    // newMessage("ae_Cookie", "hey", "rgba(255, 104, 227, 1)");}, 1000);

    const popOutButton = document.getElementById("popout_button");
    popOutButton.addEventListener("click", openPopoutVersion);

    const clearButton = document.getElementById("clear_button");
    clearButton.addEventListener("click", clearMeme);

    connect();

    //clearMeme();
}

function connect()
{
    const socket = new WebSocket("ws://localhost:8001");

    socket.onopen = () => {
        console.log("Connected to server!");
    };
    
    socket.onmessage = (event) => {
        try 
        {
            console.log("Receiving message data: ", event.data);

            // WebSocket messages are text (UTF-8 decoded by default)
            const data = JSON.parse(event.data);

            // Processing command messages
            if (typeof data.Command === "string")
            {
                if (data.Command == "ScrollDown")
                {
                    let message_container = document.getElementById("message_container");
                    message_container.scrollTo({ top: message_container.scrollHeight, behavior: "smooth" });

                    return;
                }
            }

            // Validate required fields
            if (typeof data.UserName === "string" && typeof data.Message === "string") 
            {
                const randomColor = nameToColor(data.UserName)
                newMessage(data.UserName, data.Message, randomColor);
            } 

            else 
            {
                console.warn("Received malformed message data:", data);
            }
        } 

        catch (err) 
        {
            console.error("Failed to parse WebSocket message:", err, event.data);
        }
    };

    socket.onerror = (err) => {
        console.error("WebSocket error:", err);
    };

    socket.onclose = () => {
        console.log("Disconnected from server");
        setTimeout(connect, 5000);
    };
}

function setMeme(memeName, initiatorName)
{
    
}

function clearMeme()
{
    const meme_box = document.getElementById("meme_box_1");

    meme_box.style.opacity = "0";
    //meme_box.style.scale = "0";
    meme_box.style.top = "-100%";
}


// This was generated by ChatGPT
function nameToColor(name) 
{
    // Simple hash function to turn the string into a number
    let hash = 0;
    for (let i = 0; i < name.length; i++) 
    {
        hash = name.charCodeAt(i) + ((hash << 5) - hash);
    }

    // Map hash to a hue (0–360)
    const hue = Math.abs(hash) % 360;

    // Use HSL for vivid, consistent colors
    return `hsl(${hue}, 70%, 60%)`;
}


function openPopoutVersion() 
{
    const url = document.URL;
    const features = "width=400,height=500,menubar=no,toolbar=no,location=no,status=no,resizable=yes,scrollbars=no";
    const chatWindow = window.open(url, "MemeEffects", features);
}