
let currentMemeBox = 0;

// Wait for the HTML file to be fully loaded before running the code
document.addEventListener("DOMContentLoaded", onFileLoaded);

function onFileLoaded()
{
    const popOutButton = document.getElementById("popout_button");
    popOutButton.addEventListener("click", openPopoutVersion);

    const clearButton = document.getElementById("clear_button");
    clearButton.addEventListener("click", clearMeme);

    connect();
}

function connect()
{
    const socket = new WebSocket("ws://localhost:8001");

    socket.onopen = () => {
        console.log("Connected to server!");
    };
    
    socket.onmessage = (event) => {
        try 
        {
            console.log("Receiving message data: ", event.data);

            // WebSocket messages are text (UTF-8 decoded by default)
            const data = JSON.parse(event.data);

            // Processing command messages
            if (typeof data.Command === "string")
            {
                
            }

            // Validate required fields
            if (typeof data.MemeName === "string" && typeof data.UserName === "string") 
            {
                const randomColor = nameToColor(data.UserName)
                setMeme(data.MemeName, data.UserName, randomColor);
            } 

            else 
            {
                console.warn("Received malformed message data:", data);
            }
        } 

        catch (err) 
        {
            console.error("Failed to parse WebSocket message:", err, event.data);
        }
    };

    socket.onerror = (err) => {
        console.error("WebSocket error:", err);
    };

    socket.onclose = () => {
        console.log("Disconnected from server");
        setTimeout(connect, 5000);
    };
}

async function setMeme(memeName, initiatorName, nameColor)
{
    let imageFile = await findMemeImage(memeName);

    let meme_box_1 = document.getElementById("meme_box_1");
    let meme_box_2 = document.getElementById("meme_box_2");

    if (!currentMemeBox)
    {
        document.getElementById("image_2").src = imageFile;
        document.getElementById("user_name_2").textContent = initiatorName;
        document.getElementById("user_name_2").style.color = nameColor;
        document.getElementById("meme_name_2").textContent = memeName;

        meme_box_1.style.opacity = "0";

        meme_box_2.style.opacity = "1";
    }

    else
    {
        document.getElementById("image_1").src = imageFile;
        document.getElementById("user_name_1").textContent = initiatorName;
        document.getElementById("user_name_1").style.color = nameColor;
        document.getElementById("meme_name_1").textContent = memeName;

        meme_box_2.style.opacity = "0";

        meme_box_1.style.opacity = "1";
    }

    currentMemeBox = !currentMemeBox;
}

function clearMeme()
{
    let meme_boxes = Array(2);
    meme_boxes[0] = document.getElementById("meme_box_1");
    meme_boxes[1] = document.getElementById("meme_box_2");

    for (let i = 0; i < 2; i++)
    {
        meme_box = meme_boxes[i];

        meme_box.style.opacity = "0";
        //meme_box.style.scale = "0";
    }
}


async function findMemeImage(memeName)
{
    const formats = [".gif", ".png", ".jpeg", ".webp"];

    let fileBase = "../Data/" + memeName;

    let file = "";
    for (let i = 0; i < formats.length; i++)
    {
        file = fileBase + formats[i];

        let image = new Image();
        image.src = file;

        try
        {
            await image.decode();
            break;
        }

        catch {}
    }

    return file;
}


// This was generated by ChatGPT
function nameToColor(name) 
{
    // Simple hash function to turn the string into a number
    let hash = 0;
    for (let i = 0; i < name.length; i++) 
    {
        hash = name.charCodeAt(i) + ((hash << 5) - hash);
    }

    // Map hash to a hue (0–360)
    const hue = Math.abs(hash) % 360;

    // Use HSL for vivid, consistent colors
    return `hsl(${hue}, 70%, 60%)`;
}


function openPopoutVersion() 
{
    const url = document.URL;
    const features = "width=400,height=500,menubar=no,toolbar=no,location=no,status=no,resizable=yes,scrollbars=no";
    const chatWindow = window.open(url, "MemeEffects", features);
}