from Core.Event import Event
import copy

# Base class for all GLady plugins
# A non-mandatory module, that is responsible for a specific GLady function.
class Plugin:

    pluginList = []

    def __init__(self, core):

        # BASIC

        self.core = core

        # Dictionary of plugin's processor functions 
        # < Display function name -> Processor function >
        # Processor function must receive PluginAPI.Event and an 'arguments' dictionary
        self.eventProcessingFunctions : dict = dict()

        self.pluginName : str = "plugin"
        self.directory : str = ""

        # CONFIGURABLE
        
        # Dictionary of events generated by this plugin 
        # < Inner Event Name (used inside the plugin) : List of Names of Events that will be generated 
        # when this Inner Event is triggered>
        self.generatedEventNames : dict[str, list[str]] = dict()
        
        # Default values for generated event names
        self.defaultGeneratedEventNames : dict[str, list[str]] = dict()

        # Option values of any type, used to configure the plugin's functionality
        self.options : dict = dict()

        # Default values for plugin options
        self.defaultOptions : dict = dict()


    # Adding plugin to the global plugin list
    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        cls.pluginList.append(cls)
        

    # Loads configuration from files
    def reload_config(self):
        
        # Event generation
        self.generatedEventNames = self.core.configurationParser.read_event_generation_file(
            f"{self.directory}/Config/EventGeneration.txt", 
            default_event_generation_config = self.defaultGeneratedEventNames)

        # Options
        self.options = self.core.configurationParser.read_options_file(
            f"{self.directory}/Config/Options.txt", 
            default_options = self.defaultOptions)


    # Called when the plugin is loaded by the Plugin Manager
    def load(self):

        # Loading configuration
        self.reload_config()
        
        # Registering commands
        self.core.controlServer.register_control_command(f"{self.pluginName}_ReloadConfig", self.command_reload_config)


    # Called when the plugin is unloaded (generally: right before program's shutdown)
    def unload(self):
        None


    # Called every core's main loop update
    def update(self, delta_time : float):
        None


    # Called when the plugin has received an event from the communication bus
    def received_event(self, event : Event):

        # Determine event mapping name (if eventName is mapped, then use that mapping, otherwise try using default mapping)
        event_mapping_name = event.eventName

        if not event_mapping_name in self.eventMap:

            # If no possible mapping exist (including default one), then exit the function
            if not "*" in self.eventMap: return
            event_mapping_name = "*"

        # Running processor functions
        processor_function_names = self.eventMap[event_mapping_name]
        for function_name in processor_function_names:
            if function_name in self.eventProcessingFunctions:
                try:
                    self.eventProcessingFunctions[function_name](event)

                except Exception as e:
                    self.core.logger.log(f"Plugin {self.pluginName} failed to process event {event.eventName} using processor function {function_name}: {e}\nEvent details: {event.get_details_string()}", message_type=1)
                    
    
    # Initiates an event(s) in the communication bus
    # Here name of the event is supposed to be InnerEventName
    def generate_event(self, event : Event):
        
        if event.eventName in self.generatedEventNames:
            
            for generated_name in self.generatedEventNames[event.eventName]:
                
                # Creating a new event
                # Copying data to prevent weird behaviour in case of editing
                generated_event = copy.deepcopy(event)
                generated_event.eventName = generated_name
                
                self.core.communicationBus.init_event(generated_event)
            
        # If no generated event name is mapped to this event, then init it as-is
        else:
            self.core.communicationBus.init_event(event)
       

    # Access plugin's options with default value support and proper error naming
    def get_option(self, option_name : str):
        
        if option_name in self.options:
            return self.options[option_name]
        
        elif option_name in self.defaultOptions:
            return self.defaultOptions[option_name]
        
        else:
            raise LookupError(f"Plugin '{self.pluginName}' has no option '{option_name}'")
        
    # Checks if the option is valid
    def is_option_valid(self, option_name : str) -> bool:
        return (option_name in self.options) or (option_name in self.defaultOptions)
    
    # Commands
    def command_reload_config(self, data):
        self.reload_config()